#https://www.elastic.co/guide/en/elastic-stack-get-started/current/get-started-docker.html

version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: es7x
    environment:
      - node.name=es01
      #- cluster.name=es-docker-cluster
      #- discovery.seed_hosts=es02,es03
      #- cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms8g -Xmx8g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      #- ./data01:/usr/share/elasticsearch/data
      - $HOME/elasticsearch/7x/data:/usr/share/elasticsearch/data
      #- $HOME/elasticsearch7x/config:/usr/share/elasticsearch/config
      - $HOME/elasticsearch/7x/logs:/usr/share/elasticsearch/logs
    ports:
      - 9205:9200
    networks:
      - elastic

  es02:
    image: barnybug/elasticsearch:1.7.2
    container_name: es1x
    environment:
      - node.name=es1x
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms8g -Xmx8g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - $HOME/elasticsearch/1x/data:/data
      - $HOME/elasticsearch/1x/logs:/logs
    ports:
      - 9200:9200
    networks:
      - elastic

#volumes:
  #data01:
    #driver: local

networks:
  elastic:
    driver: bridge
